### ISSUE TITLE
Silverfish Prevented from Spawning

### ISSUE THREAD

**Issue by NyaSeiru** [Judge40/BetterMobGriefingGameRule#17] opened 2017-12-31 23:36 UTC
Isolated to Minecraft 1.12.2, Forge: 14.23.1.2582, no other mods in build.

Mod appears to be preventing Silverfish from spawning naturally or forcibly (egg spawner, monster spawner blocks or creative summon command), even when no settings are changed or even setting true to silverfish directly.

**Comment by Judge40** [comment] 2018-03-26 15:22
Duplicate of #18

**Closed as completed** 2018-04-01 10:13 UTC
Labels: bug, 1.12.2
